"""DEPRECATED GENERATED PARSER

This module was generated by ANTLR from `oberon.g4`. The project now uses the
handwritten `parser.py` together with the approved `grammar.ebnf` as the
canonical grammar and parser implementation.

The generated ANTLR parser is retained only for reference. Do not import
`parser_antlr` from the compiler pipeline; the codebase imports `Parser` from
`parser.py`.
"""

def parse_antlr(source: str):
    raise RuntimeError("ANTLR parser is disabled. Use `parser.py` and `grammar.ebnf`.")