# Generated by ANTLR4 - run: antlr4 -Dlanguage=Python3 oberon.g4
# Then import and use as below

from antlr4 import *
from oberonLexer import oberonLexer
from oberonParser import oberonParser
from oberonListener import oberonListener
from ast import *

class ASTBuilder(oberonListener):
    def __init__(self):
        self.stack = []

    def exitProgram(self, ctx):
        name = ctx.IDENTIFIER(0).getText()
        declarations = self.stack.pop() if self.stack else []
        statements = self.stack.pop() if self.stack else []
        self.stack.append(Program(name, declarations, statements))

    def exitDeclarations(self, ctx):
        decls = []
        for child in ctx.children:
            if hasattr(child, 'accept') and self.stack:
                decls.append(self.stack.pop())
        self.stack.append(decls)

    # Add more exit methods for each rule, building AST nodes
    # This is simplified; full implementation needed

def parse_antlr(source: str) -> Program:
    input_stream = InputStream(source)
    lexer = oberonLexer(input_stream)
    stream = CommonTokenStream(lexer)
    parser = oberonParser(stream)
    tree = parser.program()
    builder = ASTBuilder()
    walker = ParseTreeWalker()
    walker.walk(builder, tree)
    return builder.stack[0] if builder.stack else None